### PR TITLE
Project places

### PR DESCRIPTION
**Pull request by emmairwin**
Updated to reflect June 7th meeting

### CODE REVIEW

**Comment by aserebrenik** [comment]
Some projects explicitly tag bugs suited for novices to facilitate the onboarding process. This seems to be related to the discussion about the README in the Project places file.

**Comment by dicortazar** [comment]
Oops, I didn't realize about your comment  @aserebrenik I'll open a ticket based on your comment. Sorry about this.

**Comment by GeorgLink** [comment]
Why was this closed without merging?

**Comment by GeorgLink** [comment]
Answer: The pull request was from the same branch as #21, which was merged and already accepted all the changes.

**Pull request closed without merging**
