### PR TITLE
setup di_metrics.md

### PR DESCRIPTION
**Pull request by GeorgLink**
Hi Diversity and Inclusion Workgroup,

In response to #14, I put together a di_metrics.md file.

- [ ] Please compare the list to what we have in the [google doc](https://docs.google.com/document/d/1MzDk84BL7FfHDxbFxJz39M72V2Hfc5Y6oCPhOl6woxo/edit#heading=h.hx2wqrioawbd). I was not able to transfer everything 1:1 but tried to capture the essence of our previous discussion as closely as possible.

- [ ] Please also compare the list to what the [CHAOSS metrics committee compiled](https://github.com/chaoss/metrics/blob/ac2942fef83eac63caf9e3d22fe61724b97b3944/1_Diversity-Inclusion.md) before to see if we want to keep any of those goals or metrics or questions.

- [ ] Please also compare the list to what we have in our [README.md and the meeting minutes](https://github.com/chaoss/wg-diversity-inclusion/blob/ce4c90e92b6fdfd96ab32312527c4ee9581dcdfd/README.md).

I open this up for discussion.

Best,
Georg

### CODE REVIEW

**Comment by GeorgLink** [comment]
PS: I also moved the meeting minutes from the README.md to its own file.

**Comment by germonprez** [comment]
Thanks @GeorgLink. Per your second point: 

 Please also compare the list to what the CHAOSS metrics committee compiled before to see if we want to keep any of those goals or metrics or questions.

Are you planning on keeping your own metrics list in the work group? I only ask for workflow reasons. Personally, I'd prefer to have one list (not two) across both repos.

**Comment by GeorgLink** [comment]
We will move the list to the metrics repo when accepted by the work group
members.

**Comment by emmairwin** [comment]
Flagging for others - the file to review is here:   https://github.com/GeorgLink/wg_diversity_inclusion/blob/metrics/di_metrics.md

**Comment by dicortazar** [comment]
@GeorgLink awesome work, thanks a lot for pushing this!

I'd say this is pretty aligned to the information we have in the Google Docs :).

I do have some comments on some of the areas, but what do you think if we merge this and then start some polishing process after this?

**Comment by dicortazar** [comment]
After today's meeting, we agreed in merging this and adding other PRs to the left details.

Thanks a lot for your work and time!

**Pull request merged**
