### PR TITLE
add onboarding temporarily in leadership.

### PR DESCRIPTION
**Pull request by GeorgLink**
See meeting minutes from 9/19/2018

(copied from minutes)
Nicole: Is the mentorship analysis / concept already incorporated in the current set of metrics we have so far? (Leadership Category)
Add questions related to the existence of mentorship programs, and check if there are mentorship programs focused on underrepresented groups of people.
Eg: Outreachy or GSoC, or internal programs such as the Upstream Program by the OpenStack Foundation.
Study on patterns or anti patterns, work done at Kubernetes
Look at the rate of newcomers
Result from OpenStack:
Mentoring via Outreachy lead to longer participation
Need to explore this metric
Data from Google Summer of Code as well
Level of contribution and longevity were positively impacted
Both K8s and OS have solid ways of welcoming newcomers
Want to make sure this is reflected in some way
On boarding may be seen as the umbrella for helping newcomers, and mentorship might be part of this. Others may apply.
Metrics:
Type of onboarding: 1:1, 1:x, groups
Ascending membership ladders (e.g. member -> reviewer -> maintainer)
Inclusion in decision-making (e.g. elections, OWNERS files)
Governance leadership: SIG leader, Steering Committee membership
In speed mentoring program (OS, and Linux communities)
Paris Pittman on mentoring: https://thewomenintechshow.com/2018/06/11/scaling-mentorship-in-kubernetes-with-paris-pittman/

### CODE REVIEW

**Comment by emmairwin** [comment]
This is saying that onboarding is role of leadership?  Or falls under leadership?

**Comment by GeorgLink** [comment]
No, it is a placeholder only. During the meeting, we were discussing to put
onboarding as a new focus area.

**Comment by emmairwin** [comment]
@GeorgLink can you please merge your local codebase with the latest changes and commit ?   I'l lbe able to merge then. thank you!

**Comment by GeorgLink** [comment]
Thanks Emma. I merged the local codebase. Merge conflict is resolved

**Comment by emmairwin** [comment]
Thank again!

**Pull request merged**
