### PR TITLE
initial commit  - inclusive leadership

### PR DESCRIPTION
**Pull request by emmairwin**
Inclusive leadership.
Once approved, I'll write a blog post about how to apply these as we've discussed in #252

### CODE REVIEW

**Comment by GeorgLink** [comment]
Thanks @emmairwin 

At a glance, I see that we want to update the template. 

I also think we should review the metric during a D&I WG call before merging.
Do you have time to join a D&I WG call to work with us through the metric?

Best,
Georg

PS: We would also need a valid DCO sign-off before we can merge. I documented the process in this [CONTRIBUTING.md](https://github.com/chaoss/governance/blob/master/CONTRIBUTING.md) file but am more than happy to jump on a call with you any time (after my vacation which is next week).

**Comment by emmairwin** [comment]
Thanks @GeorgLink 

- Can you please share what updates are needed for the template and I can update accordingly?  That might be helpful in advance to get in a shape CHAOSS members recognize- 
- For the foreseeable future, am not available during the timeslot the working group meets, but I can certainly record a short video description, and take questions asynchronously.  Please let me know if this feels like an acceptable substitute. 
- I can review DCO .
- Related to DCO though, this feels like all with merge privileges should be aware of the condition (how to request it, why it exists etc)? Perhaps I should no longer have that permission, but it might be better, long-term to have it documented as a maintainer requirement for permission (type thing).

Thanks!

**Comment by germonprez** [comment]
@GeorgLink could you take a look at this?

**Comment by GeorgLink** [comment]
@emmairwin, thank you for proposing this metric text. I reviewed it and modeled it after the [CHAOSS Metric Template](https://github.com/chaoss/metrics/blob/master/resources/metrics-template.md).

Are you okay with the changes I made?

I will ask others to review this also during the weekly meeting on Wednesday.

**Comment by emmairwin** [comment]
Hi @germonprez @GeorgLink thanks for review, sorry where do I find your modifications?
I realize, yes, the format is different, I found it a bit challenging to format with the existing, but looking forward to seeing your proposed changed.

**Comment by GeorgLink** [comment]
Hi @emmairwin,

On today's D&I WG call, we discussed this metric, made some more modifications, and @Nebrethar will take a pass at turning the checklist into questions so that it aligns better with the other metrics we have. The working google doc version of the metric is here:
https://docs.google.com/document/d/1_GT6HghiYFwGL4KwKZL2lCAdnTc5jBPuIVxLGOmphUw/edit?usp=sharing


PS: I had previously made the changes directly in this PR, which should show on your fork, but now we are working in the [google doc](https://docs.google.com/document/d/1_GT6HghiYFwGL4KwKZL2lCAdnTc5jBPuIVxLGOmphUw/edit?usp=sharing).

**Comment by emmairwin** [comment]
Thanks for the update, and time taken to move this into an aligned structure, a first pass it looks great. I left one comment  - which I think is probably general

**Comment by GeorgLink** [comment]
Thanks @emmairwin!

**Comment by emmairwin** [comment]
Thumbs up thank you!

**Comment by GeorgLink** [comment]
Thanks @emmairwin, I'll merge it and get this ready for the next metric release.

**Review by bitcras — APPROVED** [review]

**Review by bitcras — APPROVED** [review]

**Pull request merged**
