### PR TITLE
Update next meeting date in README.md

### PR DESCRIPTION
**Pull request by GeorgLink**

### CODE REVIEW

**Comment by GeorgLink** [comment]
@dicortazar can you merge this please?

**Comment by germonprez** [comment]
@dicortazar, do you want me to take care of this? I'd prefer to leave it to you as a person heading up this WG

**Comment by dicortazar** [comment]
I'll do it, thanks for the reminder @germonprez . Said this, I'm open that anyone else join the discussions :)

**Comment by dicortazar** [comment]
Sorry for the delay by the way :/.

**Comment by GeorgLink** [comment]
Thanks @dicortazar

**Pull request merged**
