### PR TITLE
Add Resource Pages

### PR DESCRIPTION
**Pull request by GeorgLink**
Per our call yesterday, I copied the template we had into markdown and linked out to the resource page from the goal page. 

I started with Project Places and will update the pull request with the other goals.

- [x] Project Places
- [x] Communication
- [x] Contribution
- [ ] Events
- [ ] Governance
- [ ] Leadership
- [ ] Recognition

### CODE REVIEW

**Comment by emmairwin** [comment]
@dicortazar can we please get this merged?  It's a blocker for work @akshitac8 and I want to propose (or add me as maintainer, happy to do that)

Thanks!

**Comment by dicortazar** [comment]
This has been already merged up to the status of today. Shall we close this and keep adding other PRs? I would suggest to continue tracking the list of PRs in a ticket and not in a PR.

PRs should be concise and small to help in the review process :).

@emmairwin it would be good to have more maintainers definitively. I asked @GeorgLink about this as well. But let's discuss this in our next meeting if that's ok for you all.

Thanks!

**Comment by GeorgLink** [comment]
@dicortazar 

> This has been already merged up to the status of today.

I don't understand your message. This pull request is "open" as I'm writing these lines. That is not merged.

> PRs should be concise and small to help in the review process :).

This PR is concise and small. It only adds resource pages. This requires touching a lot of files.

**Comment by emmairwin** [comment]
So while I think prefixing file names as a way to categorize (vrs folders) is less than ideal, this is all a great step forward, and will inform our next steps.

Thanks for your patience.

**Pull request merged**
