### PR TITLE
Events Update to July 6th meeting

### PR DESCRIPTION
**Pull request by emmairwin**

### CODE REVIEW

**Comment by emmairwin** [comment]
We need to add this as a guide as well: https://github.com/numfocus/discover-cookbook

**Comment by dicortazar** [comment]
This looks good to me. I'll open a ticket to track the addition of the numfocus guide as suggested by @emmairwin  https://github.com/numfocus/discover-cookbook .

**Comment by GeorgLink** [comment]
Why was this closed without merging?

**Comment by GeorgLink** [comment]
Answer: The pull request was from the same branch as #21, which was merged and already accepted all the changes.

**Pull request closed without merging**
