### PR TITLE
Added Time/attention Diversity to Objectives list

### PR DESCRIPTION
**Pull request by Erioldoesdesign**
Gave the first try at explaining/describing time/attention diversity & inclusion. Would appreciate feedback/comments specifically from folks who self-describe as in a 'caring role' to see if it captures how best to include you :)

Signed-off-by: Eriol Fox eriolfox@hotmail.com

### CODE REVIEW

**Comment by germonprez** [comment]
@Erioldoesdesign I love the addition. There seems to be an issue with the DCO. Could you double check that?

**Comment by Erioldoesdesign** [comment]
@GeorgLink yeah....I'm not sure what to do with the DCO bot so it might take me a while to figure out!

**Comment by Erioldoesdesign** [comment]
It might be because I don't have a local instance of the repo and didn't do the PR via command line but just editing the .md I'll...try to do this later

**Comment by germonprez** [comment]
No problem :) Maybe @ElizabethN has some insight on how to fix this...

**Comment by ElizabethN** [comment]
Since @Erioldoesdesign added her sign-off info, but it still would not accept the DCO through the system, and because we are under a bit of a time constraint, I'm going to set this DCO to pass to keep this moving forward. (I thought maybe if I added a small change it would accept my sign off but no :dice:.) So I'll just force it through this time. Sorry if that's against protocol! :pray: :heart:

**Pull request merged**
