### PR TITLE
add contribution.md

### PR DESCRIPTION
**Pull request by akshitac8**
Thank you for the detailed description :) I have linked the proper blog which details the git commands and its description respectively.
Do let me know further changes needed :)
sorry, the PR #50 got closed accidentally. I have created a new PR in the reference of issue #32.

### CODE REVIEW

**Comment by GeorgLink** [comment]
@akshitac8 can you re-open #50 again?

This file reads like the contribution.md file from the governance repository. I liked what you did before in terms of changing the language to speak directly to people who want to contribute to the workgroup. Any chance you can get your previous file back and improve on it?

**Comment by akshitac8** [comment]
@GeorgLink The file is same. I always keep a draft of the files. Just added few basic git commands as example from governance repo. I have made some more changes. Do let me know if any further needed. :)

**Comment by dicortazar** [comment]
@akshitac8 , @GeorgLink  thanks for this great discussion and moving forward the issue.

It seems that using the contributing.md name is becoming kind of a standard (example of this at https://blog.github.com/2012-09-17-contributing-guidelines/). And the contributing.md file is linked in some cases automatically from some GitHub pages in the same way that everyone expects a README.md file.

My suggestion is to rename the file from contribution.md to CONTRIBUTING.md.

**Comment by akshitac8** [comment]
Done :)

**Comment by akshitac8** [comment]
@dicortazar are there any other changes needed in the guide styles? :slightly_smiling_face:

**Comment by emmairwin** [comment]
Hi @akshitac8 can you please change the file name to CONTRIBUTING.md ([standard](https://emmairwin.github.io/learning-open-source/articles/opening-your-project/setting-up/))  from CONTRIBUTION.md 
'

Thank you!

**Comment by akshitac8** [comment]
I have already changed the name :)

**Comment by emmairwin** [comment]
@dicortazar if you update my permissions I can merge :)

**Comment by emmairwin** [comment]
Thanks for this @akshitac8

**Pull request merged**
