### PR TITLE
Recommendations for Description and Objectives for Project Burnout

### PR DESCRIPTION
**Pull request by amcasari**
In response to PR #319:

Slight reformatting suggestions:

Changed in-line lists to a bull list
Editing multiple sentences into a complex sentence
Slight editing suggestions

### CODE REVIEW

**Comment by Nebrethar** [comment]
Looks good to me 😁 Thank you for the PR! :)

**Comment by LawrenceHecht** [comment]
I do not think the metric should be used to help individuals identify signs of burnout and make healthy life decisions related to project activities. I'll create two questions that address that approach, but they will be for "self-assessment" and not actually be used for data collection.

**Review by GeorgLink — APPROVED** [review]
LGTM

**Comment by GeorgLink** [comment]
Thanks @amcasari !

**Pull request merged**
