### PR TITLE
fix license per Project Charter to MIT

### LINKED ISSUE #149: License on repository not complient with CHAOSS charter
The CHAOSS charter states in section 8.2.3:
> All contributions to implementation-agnostic metrics and standards, including associated scripts, SQL statements, and documentation, will be received and made available under the MIT License.

I never noticed it, but our workgroup repository has a GPL-3.0 license.

This issue is to discuss whether we can change the license in the repository, since it should have been MIT from the beginning but people contributed, maybe thinking it was GPL-3.0.

### PR DESCRIPTION
**Pull request by GeorgLink**
Licensing metrics and non-code contributions is tricky, but with help of Linux Foundation counsel, the CHAOSS Project Charter requires that we use MIT license. 

This pull request fixes #149 and re-licenses everything in this repository from GPL-v3 to MIT

It would be great (if not required) that all contributors to the repository agree to this re-licensing by commenting on this pull request.

### CODE REVIEW

**Comment by GeorgLink** [comment]
The repository has currently eight contributors. Here is a check list to track who agreed:

- [X] @GeorgLink 
- [ ] @emmairwin 
- [ ] @geekygirldawn
- [ ] @dicortazar
- [ ] @akshitac8
- [ ] @drashti4
- [ ] @7UTpH
- [ ] @dunebuggie

**Comment by geekygirldawn** [comment]
I am pretty sure that we **do** actually need all of these people to agree to the license change.

**Comment by drashti4** [comment]
I'm agree. Licence is fundamental of any open-source project.

**Comment by dunebuggie** [comment]
I agree! 🙂

**Comment by dicortazar** [comment]
Hey, not a big fan of this change, but that's alright for me... this is in the Charter ;).

**Comment by dicortazar** [comment]
It seems we're missing @germonprez here as displayed in the dashboard: https://chaoss.biterg.io/goto/98344dffe97762e90e6d10519f681ea6 .

Cheers

**Comment by GeorgLink** [comment]
Thanks, added him to the list at the top. Also added @vchrombie because he recently submitted a pull request.

**Comment by vchrombie** [comment]
I too agree with your point. :slightly_smiling_face:

**Comment by emmairwin** [comment]
updated with my agreement

**Comment by GeorgLink** [comment]
Lazy consensus was announced and obtained on mailing list:
https://lists.linuxfoundation.org/pipermail/chaoss-diversity-inclusion/2019-April/000122.html

**Pull request merged**
