### PR TITLE
Add contribution.md

### PR DESCRIPTION
**Pull request by akshitac8**
@GeorgLink It would be great if could help me with adding the [last comments](https://github.com/chaoss/wg-diversity-inclusion/issues/32) with the description in this file. :slightly_smiling_face:

### CODE REVIEW

**Comment by GeorgLink** [comment]
@akshitac8 how can I help?

**Comment by GeorgLink** [comment]
fixes #32

**Comment by akshitac8** [comment]
Are the contents added in the contributing.md correct?

**Comment by GeorgLink** [comment]
one more comment on branches and pull requests. I don't know if the connection and importance are coming through. We want branches for distinct changes so that pull-requests are 'pure' and can be reviewed for different change separately.

**Comment by GeorgLink** [comment]
>I had few questions,
>
> 1.  Are the contents added in the contributing.md correct?
> 2.  The comments mentioned in #32 correctly mentioned in the file?

1. Yes, although I would like the step-by-step instructions with the specific git commands. -- if we are duplicating the process, we should link out to the other file; if we are doing something different, then we should provide the exact commands to be executed.
2. Yes

**Comment by akshitac8** [comment]
Thank you for the detailed description :)

**Pull request closed without merging**
