### PR TITLE
Optimized Images

### PR DESCRIPTION
**Pull request by vardaan-raj**

### CODE REVIEW

**Comment by germonprez** [comment]
Could you please include a description for describing the PR? Thanks!

**Comment by vardaan-raj** [comment]
Yes sure !

I will do that shortly

**Comment by vardaan-raj** [comment]
> Could you please include a description for describing the PR? Thanks!

Imgbot is a friendly robot that optimizes your images and saves you time. Optimized images mean smaller file sizes without sacrificing quality. ... As you work on your project, Imgbot works alongside you to keep your images optimized. Imgbot uses lossless compression by default. 

I have optimized your images by compressing their size without compromising their quality which will help better manage space.

**Comment by vardaan-raj** [comment]
> Could you please include a description for describing the PR? Thanks!

PS. Sorry for the late reply, I got really busy.
Hope you understand

**Comment by germonprez** [comment]
I think they look fine as compared to the original images. Thanks!

**Comment by vardaan-raj** [comment]
My pleasure Matt!

**Pull request merged**
