### PR TITLE
Filename changes

### LINKED ISSUE #101: File Naming Standard
I notice that we are naming files one of two ways:

with-dashes.md
with_underscores.md

I would like to propose the standard be for dashes.   If there is agreement, then the task is to update all files with underscores to dashes.

Thanks

### PR DESCRIPTION
**Pull request by UTpH**
Replaced '_' with '-' in all files
fixes #101

### CODE REVIEW

**Comment by UTpH** [comment]
Sure. I will work update that as well.

**Comment by GeorgLink** [comment]
Thank you @UTpH for putting this together. Let me know if you have any further questions.

**Comment by emmairwin** [comment]
@UTpH thanks SO MUCH for working on this!!!

**Comment by UTpH** [comment]
I have a few observations:-
1. I think most of the hits above pertain to my initial query of:-
https://github.com/chaoss/wg-diversity-inclusion/issues/101#issuecomment-457748453
especially regarding the change in the name of folders(like focus_areas)
2. The following link seems to show up during grep and I can't seem to locate it
https://github.com/chaoss/wg-diversity-inclusion/blob/master/di_metrics.md

**Comment by geekygirldawn** [comment]
> @GeorgLink
> I have a few observations:-
> 
> 1. I think most of the hits above pertain to my initial query of:-
>    [#101 (comment)](https://github.com/chaoss/wg-diversity-inclusion/issues/101#issuecomment-457748453)

I think it's actually a bit different. The output from grep shows which files link to filenames that have likely been changed. We do quite a bit of linking within the markdown pages to other files within the repository. For example, you changed this filename.

    focus_areas/contribution/collaboration_style.md → focus_areas/contribution/collaboration-style.md

This line from the grep shows that the file whose name was changed was linked to from focus_areas/contribution/README.md, so we also also need to update the contents of focus_areas/contribution/README.md with the new link.

    ./focus_areas/contribution/README.md:[Collaboration Style](collaboration_style.md) | How inclusive is community collaboration? (what we mean by collaboration needs better defined)

If you have a look at focus_areas/contribution/README.md, you can see that lines 7 - 10 of the file have links to files with underscores that are being changed to dashes in your pull request.

Does this help?

>    especially regarding the change in the name of folders(like focus_areas)
> 2. The following link seems to show up during grep and I can't seem to locate it
>    https://github.com/chaoss/wg-diversity-inclusion/blob/master/di_metrics.md

Good catch! This is a broken link - probably because we renamed the file and forgot to update references to that file when we renamed it. It appears within these files focus_areas/README.md and focus_areas/events/attendee_demographics.md. It should be changed to https://github.com/chaoss/wg-diversity-inclusion/blob/master/demographic-data/README.md

Again, thank you so much for all of the work you've put into this! We really appreciate it!

**Comment by GeorgLink** [comment]
+1 to Dawn's response.

Thank you @UTpH for following through.

**Comment by UTpH** [comment]
Committed required changes! #155

**Comment by GeorgLink** [comment]
Thank you @UTpH!

**Pull request merged**
