### PR TITLE
Standardized Repo Structure

### PR DESCRIPTION
**Pull request by yash2002109**
In reference to issue #346. I have made the following changes to the repository to ensure it follows the template.

1. Renamed metric filenames
2. Renamed focus-area subfolders
3. Updated links to those files in README.md
4. Updated the LICENSE year.

### CODE REVIEW

**Review by GeorgLink — APPROVED** [review]
This is great. Thanks @yash2002109 

Merging is blocked by website. @klumb can you please merge this PR and update the metrics pages that pull from the markdown?

**Comment by GeorgLink** [comment]
Ping @klumb -- please merge and update website

**Comment by germonprez** [comment]
@klumb does this require your input?

**Comment by klumb** [comment]
Add this to my Action Items

**Pull request merged**
